-- FAMILIAS
INSERT INTO familias(cod, descripcion) VALUES (1, 'SERVICIOS PERSONALES');
INSERT INTO familias(cod, descripcion) VALUES (2, 'MATERIALES Y SUMINISTROS');
INSERT INTO familias(cod, descripcion) VALUES (3, 'SERVICIOS NO PERSONALES');
INSERT INTO familias(cod, descripcion) VALUES (4, 'MAQUINAS, EQUIPOS Y MOBILIARIOS NUEVOS');
INSERT INTO familias(cod, descripcion) VALUES (5, 'TIERRAS, EDIFICIOS Y OTROS BIENES DE USO');
INSERT INTO familias(cod, descripcion) VALUES (6, 'CONSTRUCCIONES, MEJORAS Y REPARACIONES EXTRAORDINARIAS');
INSERT INTO familias(cod, descripcion) VALUES (10, 'BIENES DE TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION');
INSERT INTO familias(cod, descripcion) VALUES (11, 'OTROS GASTOS');
INSERT INTO familias(cod, descripcion) VALUES (12, 'PRODUCTOS EXCLUIDOS DEL CATALOGO UNICO DE BIENES Y SERVICIOS');

-- SUBFAMILIAS
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (1, 1, 'SERVICIOS PERSONALES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 1, 'ALIMENTOS Y PRODUCTOS AGROPECUARIOS, FORESTALES Y MARITIMOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 2, 'MINERALES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 3, 'PRODUCTOS TEXTILES, DE VESTIR Y CUERO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 4, 'PRODUCTOS DE PAPEL, LIBROS, DOCUMENTOS  IMPRESOS Y DIGITALES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 5, 'PRODUCTOS ENERGETICOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 6, 'PROD. QUIMICOS Y CONEXOS EXCEPTO MEDIC.Y ANTISEP. USO HUMANO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 7, 'PRODUCTOS MINERALES NO METALICOS Y DE MADERA');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 8, 'PRODUCTOS METALICOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 9, 'OTROS MATERIALES Y SUMINISTROS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 10, 'PRODUCTOS DE USO MARINO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 12, 'REPUESTOS Y ACCESORIOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (2, 13, 'PROD. QUIM. Y CONEXOS-MEDICAMENTOS Y ANTISEPTICOS USO HUMANO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 1, 'SERVICIOS BASICOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 2, 'PUBLICIDAD, IMPRESIONES Y ENCUADERNACIONES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 3, 'PASAJES, VIATICOS Y OTROS GASTOS DE TRASLADO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 4, 'TRANSPORTE Y ALMACENAJE');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 5, 'ARRENDAMIENTOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 6, 'TRIBUTOS, MULTAS, RECARGOS, SEGUROS Y COMISIONES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 7, 'SERVICIOS CONTRATADOS PARA MANTENIM.Y REPARACIONES MENORES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 8, 'SERVICIOS PROFESIONALES CONTRATADOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 9, 'OTROS SERVICIOS CONTRATADOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (3, 10, 'SERVICIOS DE TECNOLOGIAS DE LA INFORMACION Y COMUNICACION');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 1, 'MAQUINARIAS Y EQUIPOS DE PRODUCCION');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 2, 'MAQUINAS Y EQUIPOS DE OFICINA Y SIMILARES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 3, 'EQUIPOS MEDICOS, SANITARIOS, ODONTOLOGICOS Y CIENTIFICOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 4, 'EQUIPOS EDUCACIONALES, CULTURALES Y RECREATIVOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 5, 'EQUIPOS DE TRANSPORTE');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 6, 'EQUIPOS DE COMUNICACIONES EXCEPTO TELEFONIA');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 7, 'MOTORES Y PARTES PARA REEMPLAZO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 8, 'MOBILIARIO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (4, 9, 'OTRAS MAQUINAS, EQUIPOS Y MOBILIARIOS NUEVOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (5, 1, 'TIERRAS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (5, 2, 'EDIFICIOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (5, 3, 'MAQUINAS, EQUIPOS Y MOBILIARIO EXISTENTE');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (5, 4, 'SEMOVIENTES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (5, 5, 'ACTIVOS FINANCIEROS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (5, 6, 'OTRAS TIERRAS, EDIFICIOS Y OTROS BIENES DE USO');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 1, 'VIAS DE COMUNICACION');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 2, 'EDIFICACIONES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 3, 'OBRAS HIDRAULICAS, HIDROELECTRICAS, ELECTRICAS Y SANITARIAS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 4, 'OBRAS URBANISTICAS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 5, 'INSTALACIONES DE TRASMISION Y DISTRIBUCION');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 6, 'MEJORAS DE TIERRAS Y PLANTACIONES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 7, 'PERFORACIONES Y EXPLORACIONES MINERAS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 8, 'REPARACIONES MAYORES Y EXTRAORDINARIAS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (6, 9, 'INSTALACION DE SERVICIOS LOCALES');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (10, 43, 'INFRAESTRUCTURA TECNOLOGICA');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (11, 1, 'OTROS GASTOS');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (12, 1, 'PRODUCTOS DE USO EXCLUSIVOS DE UTE, SIN CRITERIOS ARCE');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (12, 2, 'PRODUCTOS DE USO EXCLUSIVO DE ANCAP, SIN CRITERIO ARCE');
INSERT INTO subfamilias(fami_cod, cod, descripcion) VALUES (12, 3, 'PRODUCTOS DE USO EXCLUSIVO DE ANTEL, SIN CRITERIO ARCE');
