spring.application.name=reto-backend-febrero2026

# Datasource
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mail.to=${MAIL_TO}

# Scheduling
spring.task.scheduling.enabled=true
scheduler.licitaciones.cron=${SCHEDULER_CRON:0 0 6 * * MON-FRI}

# Error
server.error.include-message=always

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

# ARCE RSS default filters (Strategy por defecto)
arce.rss.default.family-cod=3
arce.rss.default.subfamily-cod=10

server.forward-headers-strategy=framework