package com.example.reto_backend_febrero2026.subclase;

import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum SubclaseModel {
	ESTUFAS_CALEFACTORES_TERMOTANQUES(4, 2, 9, 4, "ESTUFAS CALEFACTORES Y TERMOTANQUES"),
	INSTALACION_EQUIPOS_CALEFACCION_REFRIGERACION(3, 9, 4, 8, "INSTALACION DE EQUIPOS DE CALEFACCION Y REFRIGERACION"),
	PARTES_REEMPLAZO_EQUIPOS_CONTROL_ASISTENCIA(4, 7, 3, 6, "PARTES DE REEMPLAZO PARA EQUIPOS DE CONTROL DE ASISTENCIA ELECTRO MECANICOS"),
	MANTENIMIENTO_REPARACION_ESTRUCTURAS_METALICAS(3, 7, 2, 12, "MANTENIMIENTO Y REPARACION DE ESTRUCTURAS METALICAS"),
	AFILIACION_ORGANISMOS_SUSCRIPCIONES(3, 9, 9, 33, "AFILIACION A ORGANISMOS NACIONALES E INTERNACIONALES, Y/O SUSCRIPCIONES"),
	ACCESORIOS_EQUIPOS_CINEMATOGRAFIA_FOTOGRAFIA(4, 4, 9, 4, "ACCESORIOS PARA EQUIPOS DE CINEMATOGRAFIA Y FOTOGRAFIA"),
	ELEMENTOS_ILUMINACION_ESCENARIOS(2, 9, 3, 10, "ELEMENTOS PARA ILUMINACION DE ESCENARIOS Y SIMILARES"),
	MANTENIMIENTO_REPARACION_CARTELES_LUMINOSOS(3, 7, 2, 13, "MANTENIMIENTO Y REPARACION DE CARTELES LUMINOSOS"),
	TRATADO_SUELO(6, 6, 9, 1, "TRATADO DE SUELO"),
	ACONDICIONAMIENTO_INMUEBLES(6, 8, 1, 2, "ACONDICIONAMIENTO DE INMUEBLES"),
	REPARACIONES_OBRAS_FUNERARIAS_MONUMENTALES(6, 8, 9, 1, "REPARACIONES EN  OBRAS FUNERARIAS Y MONUMENTALES"),
	REPARACION_INSTALACION_EQUIPOS_MAQUINAS(6, 8, 3, 1, "REPARACION O INSTALACION DE EQUIPOS O MAQUINAS"),
	ARRENDAMIENTO_MAQUINAS_EQUIPOS_SERVICIO_GASTRONOMICO(3, 5, 4, 10, "ARRENDAMIENTO DE MAQUINAS Y EQUIPOS PARA SERVICIO GASTRONOMICO"),
	DEMOLICIONES(6, 8, 1, 3, "DEMOLICIONES"),
	CONFECCION_PLACAS_FICHAS_CASINOS(3, 9, 9, 34, "CONFECCION DE PLACAS Y FICHAS PARA CASINOS"),
	SERVICIOS_PRODUCCION_TELEVISION_RADIO_MEDIOS_DIGITALES(3, 9, 9, 35, "SERVICIOS DE PRODUCCION PARA TELEVISION, RADIO Y MEDIOS DIGITALES"),
	ENVASES_METALICOS(2, 8, 9, 4, "ENVASES METALICOS"),
	MAQUINAS_USO_AGRICOLA_INDUSTRIAL(4, 1, 2, 4, "MAQUINAS PARA USO AGRICOLA-INDUSTRIAL"),
	ELEMENTOS_METALICOS_ESTRUCTURALES_CONSTRUCCION(2, 8, 4, 9, "ELEMENTOS METALICOS ESTRUCTURALES PARA LA CONSTRUCCION"),
	PRODUCTOS_QUIMICOS_LABORATORIO_FOTOGRAFICO(2, 6, 9, 13, "PRODUCTOS QUIMICOS PARA LABORATORIO FOTOGRAFICO"),
	ACCESORIOS_TERMINACIONES_MADERA_SIMILARES(2, 7, 5, 11, "ACCESORIOS Y TERMINACIONES DE MADERA Y SIMILARES"),
	MANTENIMIENTO_REPARACION_EQUIPOS_SOLDAR(3, 7, 3, 26, "MANTENIMIENTO Y REPARACION DE EQUIPOS PARA SOLDAR"),
	MISCELANEA(3, 7, 5, 18, "MISCELANEA"),
	MANTENIMIENTO_REPARACION_MAQUINAS_TRAGAMONEDAS(3, 7, 4, 23, "MANTENIMIENTO Y REPARACION DE MAQUINAS TRAGAMONEDAS (SLOT), Y ACCESORIOS"),
	PARTES_REEMPLAZO_EMBARCACION(4, 7, 6, 201, "PARTES DE REEMPLAZO PARA EMBARCACION"),
	SERVICIO_CONTROL_PLAGA(3, 9, 9, 36, "SERVICIO DE CONTROL DE PLAGA"),
	INSTALACION_EQUIPOS_ELECTRONICOS(3, 9, 4, 10, "INSTALACION DE EQUIPOS ELECTRONICOS"),
	ARRENDAMIENTO_RECIPIENTES_CONTENEDORES_RESIDUOS(3, 5, 9, 18, "ARRENDAMIENTO DE RECIPIENTES Y CONTENEDORES PARA RESIDUOS"),
	REPARACIONES_LOCALES_DEPORTES_CULTURA_RECREATIVOS(6, 8, 9, 2, "REPARACIONES EN LOCALES DE DEPORTES, CULTURA, RECREATIVOS, ETC."),
	ARRENDAMIENTO_GENERADORES_GRUPOS_ELECTROGENOS(3, 5, 9, 19, "ARRENDAMIENTO DE GENERADORES Y GRUPOS ELECTROGENOS"),
	MANTENIMIENTO_REPARACION_EQUIPOS_INSTRUMENTOS_ELECTRONICOS(3, 7, 4, 24, "MANTENIMIENTO Y REPARACION DE EQUIPOS E INSTRUMENTOS ELECTRONICOS"),
	SERVICIOS_VARIOS_TANQUES_COMBUSTIBLES(3, 9, 9, 38, "SERVICIOS VARIOS PARA TANQUES DE COMBUSTIBLES"),
	REPARACIONES_EXTRAORDINARIAS_EDIFICACIONES_ANTIGUAS(6, 2, 9, 5, "REPARACIONES EXTRAORDINARIAS DE EDIFICACIONES ANTIGUAS"),
	SERVICIO_REPARACION_INUTILIZACION_EXTINTORES(3, 9, 9, 39, "SERVICIO DE REPARACION E INUTILIZACION DE EXTINTORES"),
	ACCESORIOS_ELEMENTOS_CONTROL_ELECTRONICO(2, 9, 9, 31, "ACCESORIOS Y ELEMENTOS PARA CONTROL ELECTRONICO"),
	CONFECCION_REPARACION_ARTICULOS_GOMA(3, 9, 9, 40, "CONFECCION Y REPARACION DE ARTICULOS DE GOMA"),
	EQUIPOS_LLAMADORES_ATENCION_PUBLICO(4, 2, 9, 2, "EQUIPOS LLAMADORES PARA ATENCION AL PUBLICO (ELECTRONICOS)"),
	SERVICIOS_GRABACIONES(3, 2, 3, 2, "SERVICIOS DE GRABACIONES"),
	MANTENIMIENTO_REPARACION_EQUIPOS_TALLER(3, 7, 4, 19, "MANTENIMIENTO Y REPARACION DE EQUIPOS DE TALLER"),
	COLOCACION_ELEMENTOS_SEÑALIZACION_VIA_PUBLICA(6, 1, 7, 4, "COLOCACION DE ELEMENTOS DE SEÑALIZACION EN LA VIA PUBLICA"),
	TRABAJOS_HORMIGON_ESTRUCTURAL(3, 7, 1, 4, "TRABAJOS EN HORMIGON (ESTRUCTURAL)"),
	CONTRATACION_MUSICOS_TECNICOS(3, 8, 9, 14, "CONTRATACION DE MUSICOS Y TECNICOS"),
	CERRAMIENTOS(2, 6, 6, 20, "CERRAMIENTOS"),
	SERVICIO_ARENADOS(3, 9, 1, 12, "SERVICIO DE ARENADOS"),
	SEMILLAS_FLORALES_ESTACIONALES(2, 1, 8, 7, "SEMILLAS FLORALES ESTACIONALES"),
	PLASTIFICADOS_SIMILARES(3, 2, 2, 7, "PLASTIFICADOS Y SIMILARES"),
	MANTENIMIENTO_REPARACION_CERRADURAS(3, 7, 9, 9, "MANTENIMIENTO Y REPARACION DE CERRADURAS"),
	INSUMOS_FOTOCOPIADORAS_FACSIMILES_IMPRESORAS(2, 9, 1, 4, "INSUMOS PARA FOTOCOPIADORAS, FACSIMILES, IMPRESORAS Y SIMILARES"),
	PLANTAS_FLORALES_ESTACION(2, 1, 9, 9, "PLANTAS FLORALES DE ESTACION"),
	PARTES_REEMPLAZO_EQUIPAMIENTO_LABORATORIO_CLINICO(4, 7, 4, 4, "PARTES DE REEMPLAZO PARA EQUIPAMIENTO DE LABORATORIO CLINICO"),
	TIMBRES_FRANQUEO_CORRESPONDENCIA(2, 4, 7, 4, "TIMBRES PARA FRANQUEO DE CORRESPONDENCIA"),
	SERVICIO_SUMINISTRO_ACTUALIZACION_INFORMACION(3, 9, 9, 28, "SERVICIO DE SUMINISTRO Y ACTUALIZACION DE INFORMACION"),
	MANTENIMIENTO_REPARACIONES_HERRERIA(3, 7, 2, 11, "MANTENIMIENTO Y REPARACIONES DE HERRERIA"),
	ARRENDAMIENTO_SERVICIO_CAJERO(3, 5, 9, 17, "ARRENDAMIENTO DE SERVICIO DE CAJERO"),
	PROYECTOS_INGENIERIA_TRANSITO(6, 1, 7, 5, "PROYECTOS  DE INGENIERIA DE TRANSITO"),
	GASTOS_PAGO_DERECHOS_AUTOR_SIMILARES(3, 8, 9, 15, "GASTOS POR PAGO DE DERECHOS DE AUTOR Y SIMILARES"),
	SERVICIO_MANTENIMIENTO_AREAS_CARACTER_COLECTIVO(3, 1, 9, 2, "SERVICIO DE MANTENIMIENTO DE AREAS DE CARACTER COLECTIVO EN INMUEBLES"),
	CONTRATACION_SERVICIOS_DIBUJO_DISEÑOS(3, 8, 9, 16, "CONTRATACION DE SERVICIOS DE DIBUJO,DISEÑOS, ETC."),
	PAPEL_MATRIZ_GLASEADO_SIMILARES(2, 4, 9, 1, "PAPEL MATRIZ, GLASEADO Y SIMILARES."),
	MANTENIMIENTO_REPARACION_EQUIPOS_MANTENIMIENTO_AREAS_VERDES(3, 7, 4, 20, "MANTENIMIENTO Y REPARACION DE EQUIPOS PARA MANTENIMIENTO DE AREAS VERDES"),
	MANTENIMIENTO_RESTAURACION_OBRAS_ARTE(3, 7, 9, 10, "MANTENIMIENTO Y RESTAURACION DE OBRAS DE ARTE"),
	SUMINISTRO_ENERGIA_ELECTRICA_AMPLIACION_INSTALACIONES(3, 1, 9, 3, "SUMINISTRO DE ENERGIA ELECTRICA Y AMPLIACION DE INSTALACIONES O REDES  ELECTRICAS"),
	SERVICIO_CONFECCION_TELA(3, 9, 9, 29, "SERVICIO DE CONFECCION EN TELA"),
	SERVICIO_GOMERIA_RECAUCHUTAJE_ALINEACION_BALANCEO(3, 7, 5, 17, "SERVICIO DE GOMERIA, RECAUCHUTAJE, ALINEACION Y BALANCEO"),
	PINTURAS_REPRODUCCIONES_GRABADOS_ACCESORIOS(2, 9, 9, 28, "PINTURAS, REPRODUCCIONES, GRABADOS, ACCESORIOS,  ETC."),
	MANTENIMIENTO_REPARACION_EQUIPOS_LIMPIEZA_AMBIENTAL(3, 7, 4, 21, "MANTENIMIENTO Y REPARACION DE EQUIPOS DE LIMPIEZA AMBIENTAL"),
	ACCESORIOS_EQUIPO_RADIOTRASMISORES(2, 9, 9, 29, "ACCESORIOS PARA EQUIPO RADIOTRASMISORES"),
	PARTES_REEMPLAZO_EQUIPOS_INDUSTRIA_GASTRONOMICA(4, 7, 2, 5, "PARTES DE REEMPLAZO PARA EQUIPOS DE INDUSTRIA GASTRONOMICA"),
	SERVICIO_MANTENIMIENTO_SISTEMAS_SANEAMIENTO_COSTERO(3, 9, 9, 31, "SERVICIO DE MANTENIMIENTO DE SISTEMAS DE SANEAMIENTO COSTERO"),
	EQUINOS_EXISTENTE(5, 4, 3, 1, "EQUINOS"),
	SERVICIO_AEREO(3, 9, 9, 25, "SERVICIO AEREO"),
	SERVICIO_FUMIGACION_DESINFECCION(3, 9, 1, 11, "SERVICIO DE FUMIGACION Y DESINFECCION"),
	SERVICIO_DESPACHANTE_ADUANA_AGENTE_COMERCIO_EXTERIOR(3, 8, 9, 10, "SERVICIO DE DESPACHANTE DE ADUANA  Y AGENTE DE COMERCIO EXTERIOR"),
	SERVICIOS_FOTOGRAFIAS_FILMACIONES(3, 2, 3, 1, "SERVICIOS DE FOTOGRAFIAS Y FILMACIONES"),
	ARTICULOS_BAZAR(2, 9, 9, 26, "ARTICULOS DE BAZAR"),
	MANTENIMIENTO_REPARACION_EQUIPAMIENTO_ELECTRICO(3, 7, 3, 23, "MANTENIMIENTO Y REPARACION DE EQUIPAMIENTO  ELECTRICO (MOTORES, CARGADORES, TRANSFORMADORES, GENERADORES ETC.)"),
	MANTENIMIENTO_REPARACION_MAQUINAS_INDUSTRIALES(3, 7, 3, 24, "MANTENIMIENTO Y REPARACION DE MAQUINAS INDUSTRIALES"),
	MAQUINAS_INDUSTRIALES(4, 1, 1, 11, "MAQUINAS INDUSTRIALES"),
	ELEMENTOS_TRANSMISIONES_SERVOTRANSMISIONES_AUTOMATICAS(4, 7, 6, 12, "ELEMENTOS DE TRANSMISIONES, SERVOTRANSMISIONES Y TRANSMISIONES AUTOMATICAS"),
	ELEMENTOS_CIRCUITOS_HIDRAULICOS_BOMBAS_MOTORES(4, 7, 6, 13, "ELEMENTOS DE CIRCUITOS HIDRAULICOS, BOMBAS Y MOTORES OLEOHIDRAULICOS, VALVULAS, ACTUADORES, MANGUERAS, TUBOS, INSTRUMENTOS DE MEDICION Y CONTROL ,ETC."),
	ELEMENTOS_TREN_RODADO(4, 7, 6, 14, "ELEMENTOS DE TREN DE RODADO"),
	ELEMENTOS_IMPLEMENTOS_MAQUINARIA_MOVIMIENTO_TIERRA(4, 7, 6, 15, "ELEMENTOS DE IMPLEMENTOS DE MAQUINARIA DE MOVIMIENTO DE TIERRA, CUCHARONES, HOJAS TOPADORAS,  ESCARIFICADORES, MOVIMIENTOS, HERRAMIENTAS DE CORTE, ETC."),
	ELEMENTOS_MANDOS_FINALES_EMBRAGUES_DIRECCIONALES(4, 7, 6, 16, "ELEMENTOS DE MANDOS FINALES, EMBRAGUES DIRECCIONALES Y DIFERENCIALES DE MAQUINARIA PARA MOVIMIENTO DE TIERRA"),
	ELEMENTOS_SUPERESTRUCTURA_VEHICULOS(4, 7, 6, 17, "ELEMENTOS DE SUPERESTRUCTURA DE VEHICULOS"),
	ELEMENTOS_MECANICOS_EQUIPOS_TRABAJO(4, 7, 6, 18, "ELEMENTOS MECANICOS DE LOS EQUIPOS  DE TRABAJO, ELEVADORES, CINTAS, TORNILLOS SINFIN, REDUCTORES, ETC"),
	MANTENIMIENTO_REPARACION_AUTORADIOS(3, 7, 3, 25, "MANTENIMIENTO Y REPARACION DE AUTORADIOS"),
	UTILES_ACCESORIOS_BAÑO(2, 9, 2, 4, "UTILES Y ACCESORIOS PARA BAÑO"),
	EQUIPOS_ASTRONOMIA_ASTROFISICA(4, 3, 9, 5, "EQUIPOS PARA ASTRONOMIA, ASTROFISICA"),
	CONTRATACION_SERVICIOS_VETERINARIOS(3, 8, 9, 12, "CONTRATACION DE SERVICIOS VETERINARIOS"),
	ACCESORIOS_HERRAMIENTAS_TRABAJO_ANIMALES(2, 9, 9, 25, "ACCESORIOS Y HERRAMIENTAS DE TRABAJO CON ANIMALES"),
	ELEMENTOS_PROTECCION_SOLAR_SEGURIDAD(2, 6, 6, 18, "ELEMENTOS DE PROTECCION SOLAR Y DE SEGURIDAD"),
	LAMINAS_REPRODUCCIONES(2, 4, 5, 5, "LAMINAS Y REPRODUCCIONES"),
	EQUIPO_REPRODUCCION_ACONDICIONAMIENTO_PLANOS(4, 2, 4, 6, "EQUIPO PARA  REPRODUCCION Y ACONDICIONAMIENTO DE PLANOS"),
	MANTENIMIENTO_REPARACION_ELECTRODOMESTICOS(3, 7, 4, 18, "MANTENIMIENTO Y REPARACION ELECTRODOMESTICOS"),
	SEGUROS_ASALTO_CUSTODIA_VALORES(3, 6, 1, 8, "SEGUROS CONTRA ASALTO Y POR CUSTODIA DE VALORES"),
	SERVICIO_CERRAJERIA(3, 7, 2, 10, "SERVICIO DE CERRAJERIA"),
	CUADRERIAS(3, 9, 9, 27, "CUADRERIAS"),
	ARTEFACTOS_COCINA_COMEDOR(2, 9, 6, 2, "ARTEFACTOS DE COCINA Y COMEDOR"),
	EQUIPOS_ACCESORIOS_CERAMICA(4, 4, 9, 2, "EQUIPOS Y ACCESORIOS PARA CERAMICA"),
	POLIMEROS_PRODUCTOS_ACABADOS(2, 6, 6, 19, "POLIMEROS Y PRODUCTOS ACABADOS"),
	ENRAIZADORES(2, 6, 3, 14, "ENRAIZADORES"),
	ARRENDAMIENTO_SERVICIOS_SEÑALIZACION(3, 5, 9, 16, "ARRENDAMIENTO DE SERVICIOS DE SEÑALIZACION"),
	EQUIPAMIENTO_USO_VETERINARIO(4, 3, 9, 7, "EQUIPAMIENTO PARA USO VETERINARIO"),
	ARMAS_FUEGO_ACCESORIOS_DEFENSA_PERSONAL(2, 9, 9, 27, "ARMAS DE FUEGO Y ACCESORIOS DE DEFENSA PERSONAL"),
	ADORNOS_PORCELANA(2, 7, 4, 3, "ADORNOS DE PORCELANA"),
	MAQUINAS_EQUIPOS_TAPICERIA_COSTURA(4, 1, 1, 12, "MAQUINAS Y EQUIPOS DE TAPICERIA Y COSTURA"),
	MANTENIMIENTO_REP_TRENES_RODADO_MAQUINAS_VIALES(3, 7, 3, 16, "MANTENIMIENTO Y REP.DE TRENES DE RODADO DE MAQUINAS VIALES"),
	MANTENIMIENTO_REP_RADIADORES_MAQUINAS_VIALES(3, 7, 3, 17, "MANTENIMIENTO Y REP.DE RADIADORES DE MAQUINAS VIALES"),
	MANTENIMIENTO_REP_LUBRICACION_MAQUINAS_VIALES(3, 7, 3, 18, "MANTENIMIENTO Y REP.DE LUBRICACION DE MAQUINAS VIALES"),
	SERVICIO_CHAPA_PINTURA_MAQUINAS_VIALES(3, 7, 3, 20, "SERVICIO DE CHAPA Y PINTURA DE MAQUINAS VIALES"),
	SERVICIO_GOMERIA_MAQUINAS_VIALES(3, 7, 3, 21, "SERVICIO DE GOMERIA DE MAQUINAS VIALES"),
	ARRENDAMIENTO_EQUIPOS_COMUNICACIONES(3, 5, 9, 15, "ARRENDAMIENTO DE EQUIPOS DE COMUNICACIONES"),
	MANTENIMIENTO_REP_MECANICAS_VEHICULOS_LIGEROS_CAMIONES(3, 7, 5, 1, "MANTENIMIENTO Y REP.MECANICAS DE VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REP_SISTEMA_INYECCION_CARBURACION_AFINADO(3, 7, 5, 3, "MANTENIMIENTO Y REP.DEL SISTEMA DE INYECCION , CARBURACION Y AFINADO"),
	MANTENIMIENTO_REP_TURBOCOMPRESOR_VEHICULOS(3, 7, 5, 4, "MANTENIMIENTO Y REP.DEL TURBOCOMPRESOR PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REP_SUSPENSION_VEHICULOS(3, 7, 5, 5, "MANTENIMIENTO Y REP.DE SUSPENSION PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_LUBRICACION_VEHICULOS(3, 7, 5, 6, "MANTENIMIENTO .DE LUBRICACION PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REP_SIST_ELECTRICO_TABLERO_VEHICULOS(3, 7, 5, 7, "MANTENIMIENTO Y REP.DEL SIST.ELECTRICO Y TABLERO PARA VEHICULOS LIGEROS Y CAMIONES"),
	REPARACION_CHAPA_PINTURA_VEHICULOS(3, 7, 5, 8, "REPARACION DE CHAPA Y PINTURA PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REP_SISTEMAS_HIDRAULICOS_VEHICULOS(3, 7, 5, 9, "MANTENIMIENTO Y REP.DE SISTEMAS HIDRAULICOS PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REPARACION_TRANSMISIONES_VEHICULOS(3, 7, 5, 10, "MANTENIMIENTO Y REPARACION DE TRANSMISIONES PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REP_RADIADORES_VEHICULOS(3, 7, 5, 12, "MANTENIMIENTO Y REP. DE RADIADORES PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REP_CHASIS_CARROCERIA_VEHICULOS(3, 7, 5, 13, "MANTENIMIENTO Y REP. DE CHASIS Y CARROCERIA PARA VEHICULOS LIGEROS Y CAMIONES"),
	MANTENIMIENTO_REP_ESTRUCTURAS_METALICAS_VEHICULOS(3, 7, 5, 14, "MANTENIMIENTO Y REP. DE ESTRUCTURAS METALICAS PARA VEHICULOS LIGEROS Y CAMIONES"),
	SERVICIO_VIDRIERIA(3, 7, 2, 8, "SERVICIO DE VIDRIERIA"),
	TRABAJOS_TERMINACIONES_REVESTIMIENTOS(3, 7, 1, 3, "TRABAJOS EN TERMINACIONES (REVESTIMIENTOS)"),
	COLOCACION_MOQUETTE_VINILICOS(3, 7, 2, 9, "COLOCACION DE MOQUETTE Y VINILICOS"),
	SERVICIO_FUNEBRE(3, 9, 9, 22, "SERVICIO FUNEBRE"),
	TRANSPORTE_VALORES(3, 4, 5, 2, "TRANSPORTE DE VALORES"),
	TOLDOS_CAPOTAS_FUNDAS(2, 3, 1, 10, "TOLDOS, CAPOTAS, FUNDAS, ETC."),
	ARTICULOS_TALABARTERIA(2, 3, 4, 3, "ARTICULOS DE TALABARTERIA"),
	SERVICIO_RECAUDACION_PAGO(3, 9, 9, 23, "SERVICIO DE RECAUDACION Y PAGO"),
	IMPRESOS_PAPEL_PRESOSENSIBLE(2, 4, 3, 6, "IMPRESOS EN PAPEL PRESOSENSIBLE"),
	SERVICIO_FOTOMECANICA_DIGITAL(3, 2, 2, 6, "SERVICIO DE FOTOMECANICA DIGITAL"),
	CALDERAS_GENERADORES_VAPOR_OTROS(4, 1, 4, 3, "CALDERAS, GENERADORES DE VAPOR Y OTROS"),
	REPARACION_INSTALACION_SILENCIADORES_ESCAPE_VEHICULOS(3, 7, 5, 15, "REPARACION  E INSTALACION DE SILENCIADORES Y ELEMENTOS DE ESCAPE PARA VEHICULOS LIGEROS Y CAMIONES"),
	REPARACION_INSTALACION_SILENCIADORES_ESCAPE_MAQUINAS(3, 7, 3, 22, "REPARACION E INSTALACION DE SILENCIADORES Y ELEMENTOS DE ESCAPE DE MAQUINAS VIALES"),
	EQUIPOS_DETECCION_CONTROL_MEDIDA(4, 3, 9, 4, "EQUIPOS DE DETECCION, CONTROL Y MEDIDA"),
	MAMPARAS_SIMILARES(4, 8, 9, 4, "MAMPARAS Y SIMILARES"),
	TROQUELADORAS(4, 2, 4, 3, "TROQUELADORAS"),
	CAJA_SEGURIDAD(2, 8, 9, 2, "CAJA DE SEGURIDAD"),
	SERVICIO_DECORACION(3, 9, 9, 20, "SERVICIO DE DECORACION"),
	ARRENDAMIENTO_MAQUINAS_TROQUELADORAS_DESTRUCTORAS(3, 5, 4, 8, "ARRENDAMIENTO DE MAQUINAS TROQUELADORAS Y DESTRUCTORAS DE PAPEL"),
	ARRENDAMIENTO_FRANCOTIPO(3, 5, 4, 9, "ARRENDAMIENTO DE FRANCOTIPO"),
	FRANCOTIPOS(4, 2, 4, 4, "FRANCOTIPOS"),
	SERVICIO_LAVADO_VEHICULOS(3, 9, 1, 10, "SERVICIO DE LAVADO DE VEHICULOS"),
	ELEMENTOS_CHASIS_EXTERIOR_CABINA_PARAGOLPE(4, 7, 6, 1, "ELEMENTOS DE CHASIS EXTERIOR DE CABINA Y PARAGOLPE"),
	ELEMENTOS_EJES_DELANTEROS_TRASEROS_PORTANTE(4, 7, 6, 6, "ELEMENTOS DE EJES DELANTEROS, EJES TRASEROS Y EJES PORTANTE"),
	ELEMENTOS_FRENOS_RUEDAS(4, 7, 6, 7, "ELEMENTOS DE FRENOS Y RUEDAS"),
	ELEMENTOS_SUSPENSION_ELASTICOS(4, 7, 6, 8, "ELEMENTOS DE SUSPENSION Y ELASTICOS"),
	ELEMENTOS_DIRECCION_MECANICA_ASISTIDA(4, 7, 6, 9, "ELEMENTOS DE DIRECCION , MECANICA Y ASISTIDA"),
	ELEMENTOS_ESCAPE_MULTIPLES_TUBERIAS_SILENCIADORES(4, 7, 6, 10, "ELEMENTOS DE ESCAPE, MULTIPLES, TUBERIAS Y SILENCIADORES"),
	ELEMENTOS_EMBRAGUE_PLACAS_DISCOS_MECANISMOS(4, 7, 6, 4, "ELEMENTOS DE EMBRAGUE, PLACAS, DISCOS, MECANISMOS MECANICOS E HIDRAULICOS, PEDALERA"),
	ELEMENTOS_TRANSMISION_CAJAS_CAMBIO_REENVIO(4, 7, 6, 5, "ELEMENTOS DE TRANSMISION, CAJAS DE CAMBIO, CAJAS DE REENVIO, TOMAS DE FUERZA, ARBOLES DE TRANSMISION"),
	ELEMENTOS_SISTEMA_ELECTRICO_MOTOR_EQUIPAMIENTO(4, 7, 6, 11, "ELEMENTOS DEL SISTEMA ELECTRICO DEL MOTOR Y GRAL, EQUIPAMIENTO E INSTALACION E INSTRUMENTOS"),
	RELLENO_MINERAL(2, 2, 2, 8, "RELLENO MINERAL"),
	RODAMIENTOS_ACCESORIOS(2, 8, 3, 14, "RODAMIENTOS Y ACCESORIOS"),
	ELEMENTOS_INTERIOR_CABINA_TAPIZADOS(4, 7, 6, 2, "ELEMENTOS DE INTERIOR DE CABINA, TAPIZADOS, ASIENTOS ACCESORIOS PARA PUERTAS Y VENTANAS, CALEFACCION Y REFRIGERACION"),
	ELEMENTOS_MOTOR_INYECCION_REFRIGERACION(4, 7, 6, 3, "ELEMENTOS DE MOTOR, INYECCION, REFRIGERACION, LUBRICACION, TURBO COMPRESION, COMPRESOR DE AIRE Y SUSPENSION DEL MOTOR"),
	ARTICULOS_INSUMOS_ENSAYO_MATERIALES(2, 9, 9, 23, "ARTICULOS E INSUMOS PARA ENSAYO DE MATERIALES"),
	ELEMENTOS_DETECCION_CONTROL_MEDIDA_USO_INDUSTRIAL(2, 9, 9, 24, "ELEMENTOS DE DETECCION, CONTROL Y MEDIDA PARA USO INDUSTRIAL"),
	INSPECCIONES_ENSAYOS_PERITAJES_TECNICO(3, 9, 9, 21, "INSPECCIONES, ENSAYOS Y/O PERITAJES DE TIPO TECNICO EN LABORATORIO O CAMPO"),
	EQUIPOS_ENSAYO_MATERIALES(4, 3, 9, 3, "EQUIPOS PARA ENSAYO DE MATERIALES"),
	PISOS_ACCESORIOS_VINILICOS(2, 6, 6, 17, "PISOS Y ACCESORIOS VINILICOS"),
	INSTALACION_EQUIPOS_TRANSPORTE_VERTICALES(3, 9, 4, 7, "INSTALACION DE EQUIPOS DE TRANSPORTE VERTICALES"),
	MOBILIARIO_ESPECIFICO_SALAS_JUEGO(4, 8, 9, 2, "MOBILIARIO ESPECIFICO DE SALAS DE JUEGO"),
	EQUIPOS_IMPRENTA(4, 2, 4, 5, "EQUIPOS DE IMPRENTA"),
	MOBILIARIO_ANTIGUO(4, 8, 9, 3, "MOBILIARIO ANTIGUO"),
	PIEZAS_MUSEO(4, 4, 4, 5, "PIEZAS DE MUSEO"),
	EDIFICIOS_ACTIVIDADES_CULTURALES(5, 2, 7, 1, "EDIFICIOS PARA ACTIVIDADES CULTURALES"),
	EDIFICIOS_ACTIVIDADES_COMERCIALES(5, 2, 9, 0, "EDIFICIOS PARA ACTIVIDADES COMERCIALES"),
	TERMINALES_URBANAS_INTERDEPARTAMENTALES_REFUGIOS(5, 2, 7, 2, "TERMINALES URBANAS, INTERDEPARTAMENTALES  Y  REFUGIOS PEATONALES"),
	EMBARCACIONES_GRAN_CALADO(4, 5, 7, 3, "EMBARCACIONES GRAN CALADO"),
	ARRENDAMIENTO_EQUIPO_MICROFILMACION(3, 5, 9, 14, "ARRENDAMIENTO DE EQUIPO DE MICROFILMACION"),
	MANTENIMIENTO_REPARACION_MECANICA_MAQUINAS_VIALES(3, 7, 3, 9, "MANTENIMIENTO Y REPARACION MECANICA DE MAQUINAS VIALES"),
	MANTENIMIENTO_REP_TURBOCOMPRESOR_MAQUINAS_VIALES(3, 7, 3, 11, "MANTENIMIENTO Y REP.DEL TURBOCOMPRESOR DE MAQUINAS VIALES"),
	MANTENIMIENTO_REP_SERVOTRANSMISION_TRANSMISION_AUTOM(3, 7, 3, 12, "MANTENIMIENTO Y REP.DE SERVOTRANSMISION Y TRANSMISION AUTOM.DE MAQUINAS VIALES"),
	MANTENIMIENTO_REP_SISTEMAS_HIDRAULICOS_MAQUINAS_VIALES(3, 7, 3, 13, "MANTENIMIENTO Y REP.DE SISTEMAS HIDRAULICOS DE MAQUINAS VIALES"),
	MANTENIMIENTO_REP_PANTALLAS_CUCHARONES_CUCHILLAS(3, 7, 3, 14, "MANTENIMIENTO Y REP.DE PANTALLAS, CUCHARONES, CUCHILLAS, ETC. DE MAQUINAS VIALES"),
	REPARACIONES_EXTRAORDINARIAS_OTROS_SERVICIOS_PUBLICOS(6, 2, 7, 2, "REPARACIONES EXTRAORDINARIAS PARA OTROS SERVICIOS PUBLICOS"),
	MESAS_SILLAS_OTROS_MATERIALES(4, 8, 9, 1, "MESAS, SILLAS, ETC. DE OTROS MATERIALES"),
	EQUIPOS_RADIOCOMUNICACION(4, 6, 3, 2, "EQUIPOS DE RADIOCOMUNICACION"),
	ACCESORIOS_USO_ELECTRICO(2, 7, 4, 2, "ACCESORIOS PARA USO ELECTRICO"),
	CANALIZACIONES_ALINEACIONES(6, 1, 7, 1, "CANALIZACIONES Y ALINEACIONES"),
	DEMARCACION_PAVIMENTO_PINTURA_ESPECIALES(6, 1, 7, 3, "DEMARCACION DEL PAVIMENTO CON PINTURA ESPECIALES"),
	LINEAS_REDES_TELEFONICAS_CONSTRUCCION(6, 5, 3, 1, "LINEAS Y REDES TELEFONICAS"),
	DEFORESTACION_TERRENOS_CONSTRUCCION(6, 6, 1, 1, "DEFORESTACION DE TERRENOS"),
	PLANTACIONES_INDUSTRIALES_CONSTRUCCION(6, 6, 3, 1, "PLANTACIONES INDUSTRIALES"),
	DE_OTROS_MINERALES(6, 7, 2, 1, "DE OTROS MINERALES"),
	ANIMALES(4, 9, 0, 1, "ANIMALES"),
	GENERADORES_TRANSFORMADORES(4, 1, 4, 2, "GENERADORES Y TRANSFORMADORES"),
	ATRACTIVOS_SEXUALES(2, 6, 3, 7, "ATRACTIVOS SEXUALES"),
	COADYUVANTES(2, 6, 3, 9, "COADYUVANTES"),
	NEMATICIDAS(2, 6, 3, 10, "NEMATICIDAS"),
	REGULADORES_FISIOLOGICOS(2, 6, 3, 12, "REGULADORES FISIOLOGICOS"),
	DESINFECTANTE_SUELO(2, 6, 3, 13, "DESINFECTANTE DE SUELO"),
	ARRENDAMIENTO_ANIMALES(3, 5, 9, 12, "ARRENDAMIENTO DE ANIMALES"),
	REPARACIONES_MASCARONES_ALEGORIAS(3, 7, 9, 2, "REPARACIONES DE MASCARONES Y ALEGORIAS"),
	SERVICIOS_FIESTAS(3, 9, 9, 12, "SERVICIOS PARA FIESTAS"),
	REPARACIONES_PLACAS_TROFEOS(3, 7, 9, 3, "REPARACIONES DE PLACAS, TROFEOS, ETC"),
	PLACAS_TROFEOS_SIMILARES_NO_METALICOS(2, 9, 9, 22, "PLACAS, TROFEOS Y SIMILARES NO METALICOS"),
	COLOCACION_COLUMNAS_BANCOS_MESAS_HORMIGON(3, 9, 9, 13, "COLOCACION DE COLUMNAS, BANCOS,MESAS,ETC., DE HORMIGON, PIEDRA O SIMILARES"),
	MANTENIMIENTO_ESPACIOS_VERDES(3, 7, 9, 4, "MANTENIMIENTO DE ESPACIOS VERDES"),
	SERVICIOS_BUSCA_PERSONAS(3, 9, 9, 14, "SERVICIOS DE BUSCA PERSONAS"),
	MANTENIMIENTO_REPARACIONES_EDIFICACIONES_FUNERARIAS(3, 7, 9, 5, "MANTENIMIENTO Y REPARACIONES DE EDIFICACIONES FUNERARIAS"),
	SERVICIOS_ILUMINACION(3, 9, 9, 15, "SERVICIOS DE ILUMINACION"),
	EQUIPOS_ESPECIALES_FOTOGRAFIA(4, 4, 2, 2, "EQUIPOS ESPECIALES DE FOTOGRAFIA"),
	DIARIOS_SEMANARIOS(2, 4, 5, 1, "DIARIOS Y SEMANARIOS"),
	CONSTRUCCION_CARRETERAS_CAMINOS(6, 1, 1, 2, "CONSTRUCCION DE CARRETERAS Y CAMINOS"),
	ESTRUCTURACION_ESPACIOS_RECREATIVOS_PUBLICOS(6, 4, 2, 7, "ESTRUCTURACION DE ESPACIOS RECREATIVOS PUBLICOS ADULTOS E INFANTILES"),
	SERVICIO_BALIZAMIENTO_VALLADO(3, 9, 9, 17, "SERVICIO DE BALIZAMIENTO Y VALLADO"),
	SERVICIO_DESOBSTRUCCION_EXTRACCION_AGUA(3, 9, 9, 18, "SERVICIO DE DESOBSTRUCCION PARA EXTRACCION DE AGUA"),
	INSUMO_INDUSTRIA_METALURGICA(2, 8, 2, 2, "INSUMO PARA INDUSTRIA METALURGICA"),
	ARTICULOS_GOMA(2, 6, 1, 7, "ARTICULOS DE GOMA"),
	MANTENIMIENTO_REPARACION_COMPRESORES_EQUIPOS_NEUMATICOS(3, 7, 4, 16, "MANTENIMIENTO Y REPARACION  DE COMPRESORES Y EQUIPOS NEUMATICOS"),
	MATERIALES_CALDERAS_CALEFACCION(2, 8, 3, 13, "MATERIALES PARA CALDERAS Y CALEFACCION"),
	CAMPANAS_SALAMANDRAS_CHIMENEAS_DUCTOS(2, 8, 4, 8, "CAMPANAS, SALAMANDRAS, CHIMENEAS, DUCTOS , ACCESORIOS PARA ESTUFAS A LEÑA , ETC."),
	MANTENIMIENTO_REPARACION_BALANZAS(3, 7, 4, 17, "MANTENIMIENTO Y REPARACION DE BALANZAS"),
	CADENAS(2, 8, 1, 2, "CADENAS"),
	MATERIALES_FUNDICION_GENERAL(2, 8, 1, 8, "MATERIALES DE FUNDICION EN GENERAL"),
	ARTICULOS_ACCESORIOS_OPTICA(2, 9, 9, 18, "ARTICULOS Y ACCESORIOS DE OPTICA"),
	SERVICIO_LAVADO_PLANCHADO_TINTORERIA(3, 9, 1, 6, "SERVICIO DE LAVADO, PLANCHADO Y TINTORERIA"),
	SERVICIOS_ESPECTACULOS_PUBLICOS(3, 9, 9, 7, "SERVICIOS PARA ESPECTACULOS PUBLICOS"),
	SERVICIOS_HOSPEDAJE(3, 9, 9, 8, "SERVICIOS DE HOSPEDAJE"),
	MANTENIMIENTO_REPARACIONES_PARARRAYOS(3, 7, 2, 7, "MANTENIMIENTO Y REPARACIONES DE PARARRAYOS"),
	SERVICIOS_REPRODUCCION_FOTOGRAFICA_CONEXOS(3, 9, 9, 9, "SERVICIOS DE REPRODUCCION FOTOGRAFICA Y CONEXOS"),
	SERVICIOS_REPRODUCCION_SONORA(3, 9, 9, 10, "SERVICIOS DE REPRODUCCION SONORA"),
	OTROS_ELEMENTOS_FERRETERIA_SANITARIA(2, 9, 9, 19, "OTROS ELEMENTOS DE FERRETERIA Y SANITARIA"),
	PLAQUETAS_TROFEOS_MARCOS_ARTISTICOS(2, 7, 5, 10, "PLAQUETAS, TROFEOS, MARCOS ARTISTICOS, ETC."),
	TERMINALES_TRANSPORTE_COLECTIVO(6, 2, 9, 4, "TERMINALES PARA TRANSPORTE COLECTIVO"),
	CARNE_BLANCA_FRESCA_ELABORADA(2, 1, 3, 12, "CARNE BLANCA FRESCA Y ELABORADA"),
	CUEROS_MATERIALES_TAPICERIA_ZAPATERIA(2, 9, 9, 20, "CUEROS Y MATERIALES DE TAPICERIA Y ZAPATERIA"),
	PAPEL_PARA_OFICINA_SUBCLASE(2, 4, 1, 2, "PAPEL PARA OFICINA"),
	VALIJAS_BOLSOS_ARTICULOS_MARROQUINERIA(2, 3, 4, 1, "VALIJAS, BOLSOS, ARTICULOS DE MARROQUINERIA"),
	GUANTES(2, 3, 4, 2, "GUANTES"),
	FORMULARIOS_IMPRESOS_IMPRESORA_LASER(2, 4, 3, 5, "FORMULARIOS Y OTROS IMPRESOS PARA IMPRESORA LASER"),
	GAS_COMBUSTIBLE(2, 5, 3, 1, "GAS"),
	CARBON_MINERAL_COMBUSTIBLE(2, 5, 5, 1, "CARBON MINERAL"),
	PRODUCTOS_ENERGETICOS_ORIGEN_VEGETAL_COMBUSTIBLE(2, 5, 6, 1, "PRODUCTOS ENERGETICOS DE ORIGEN VEGETAL"),
	INSUMOS_USO_GRAFICO(2, 9, 9, 21, "INSUMOS PARA USO GRAFICO"),
	PRODUCTOS_QUIMICOS_USO_AUTOMOTRIZ(2, 6, 9, 11, "PRODUCTOS QUIMICOS PARA USO AUTOMOTRIZ"),
	ARRENDAMIENTO_EQUIPO_SEGURIDAD(3, 5, 9, 11, "ARRENDAMIENTO DE EQUIPO DE SEGURIDAD"),
	SERVICIO_LIMPIEZA_TAPIZADOS_MOQUETTE_CORTINAS(3, 9, 1, 7, "SERVICIO DE LIMPIEZA DE TAPIZADOS , MOQUETTE, CORTINAS, ETC"),
	SERVICIO_LIMPIEZA_TANQUES_COMBUSTIBLES(3, 9, 1, 8, "SERVICIO DE LIMPIEZA DE TANQUES DE COMBUSTIBLES"),
	SERVICIO_LIMPIEZA_LABORATORIOS(3, 9, 1, 9, "SERVICIO DE LIMPIEZA DE LABORATORIOS"),
	INSTALACION_EQUIPOS_SEGURIDAD_FISICA(3, 9, 4, 5, "INSTALACION DE EQUIPOS DE SEGURIDAD FISICA"),
	EMBARCACIONES_PEQUEÑO_CALADO(4, 5, 7, 1, "EMBARCACIONES PEQUEÑO CALADO"),
	EMBARCACIONES_MEDIANO_CALADO(4, 5, 7, 2, "EMBARCACIONES MEDIANO CALADO"),
	CAMIONETA_PICKUP_DIESEL(4, 5, 2, 2, "CAMIONETA PICKUP DIESEL"),
	CAMIONETA_RURAL_NAFTA(4, 5, 2, 3, "CAMIONETA RURAL NAFTA"),
	OBRAS_ELECTRICAS_CONSTRUCCION(6, 3, 5, 1, "OBRAS ELECTRICAS"),
	SANEAMIENTO_TIERRAS_CONSTRUCCION(6, 3, 6, 1, "SANEAMIENTO DE TIERRAS"),
	CAPTACION_EMBALSAMIENTO_DISTRIBUCION_AGUA_POTABLE(6, 3, 2, 1, "CAPTACION, EMBALSAMIENTO Y DISTRIBUCION DE AGUA POTABLE"),
	OBRAS_HIDRAULICAS_MENORES(6, 3, 3, 1, "OBRAS HIDRAULICAS MENORES"),
	CONSTRUCCION_EDIFICIOS_USO_PRODUCTIVO(6, 2, 3, 1, "CONSTRUCCION DE EDIFICIOS DE USO PRODUCTIVO"),
	CONSTRUCCION_EDIFICIOS_OFICINAS(6, 2, 1, 1, "CONSTRUCCION DE EDIFICIOS PARA OFICINAS"),
	CONSTRUCCIONES_EDIFICIOS_VIVIENDA(6, 2, 2, 1, "CONSTRUCCIONES DE EDIFICIOS PARA VIVIENDA"),
	REPARACIONES_EXTRAORDINARIAS_VIVIENDA(6, 2, 2, 2, "REPARACIONES EXTRAORDINARIAS EN VIVIENDA"),
	REPARACIONES_EXTRAORDINARIAS_EDIFICIO_USO_PRODUCTIVO(6, 2, 3, 2, "REPARACIONES EXTRAORDINARIAS PARA EDIFICIO DE USO PRODUCTIVO"),
	CONSTRUCCION_EDIFICACIONES_ENSEÑANZA(6, 2, 4, 1, "CONSTRUCCION  DE EDIFICACIONES PARA ENSEQANZA"),
	CONSTRUCCIONES_EDIFICACIONES_SALUD(6, 2, 5, 1, "CONSTRUCCIONES  DE EDIFICACIONES PARA LA SALUD"),
	REPARACIONES_EXTRAORDINARIAS_EDIFICACIONES_SALUD(6, 2, 5, 2, "REPARACIONES EXTRAORDINARIAS DE EDIFICACIONES PARA LA SALUD"),
	CONSTRUCCION_OTROS_SERVICIOS_PUBLICOS(6, 2, 7, 1, "CONSTRUCCION PARA OTROS SERVICIOS PUBLICOS");

	private final int famiCod;
	private final int subfCod;
	private final int clasCod;
	private final int cod;
	private final String description;

	SubclaseModel(int famiCod, int subfCod, int clasCod, int cod, String description) {
		this.famiCod = famiCod;
		this.subfCod = subfCod;
		this.clasCod = clasCod;
		this.cod = cod;
		this.description = description;
	}

	@JsonProperty("fami_cod")
	public int getFamiCod() {
		return famiCod;
	}

	@JsonProperty("subf_cod")
	public int getSubfCod() {
		return subfCod;
	}

	@JsonProperty("clas_cod")
	public int getClasCod() {
		return clasCod;
	}

	public int getCod() {
		return cod;
	}

	public String getDescription() {
		return description;
	}

	public static SubclaseModel findByCompositeCod(int famiCod, int subfCod, int clasCod, int cod) {
		for (SubclaseModel subclase : values()) {
			if (subclase.famiCod == famiCod &&
					subclase.subfCod == subfCod &&
					subclase.clasCod == clasCod &&
					subclase.cod == cod) {
				return subclase;
			}
		}
		throw new IllegalArgumentException("No Subclase found with famiCod: " + famiCod +
				", subfCod: " + subfCod + ", clasCod: " + clasCod + ", cod: " + cod);
	}

	public static SubclaseModel[] findByClase(int famiCod, int subfCod, int clasCod) {
		return Arrays.stream(values())
				.filter(subclase -> subclase.famiCod == famiCod && subclase.subfCod == subfCod && subclase.clasCod == clasCod)
				.toArray(SubclaseModel[]::new);
	}

	public static SubclaseModel[] findBySubfamilia(int famiCod, int subfCod) {
		return Arrays.stream(values())
				.filter(subclase -> subclase.famiCod == famiCod && subclase.subfCod == subfCod)
				.toArray(SubclaseModel[]::new);
	}

	public static SubclaseModel[] findByFamilia(int famiCod) {
		return Arrays.stream(values())
				.filter(subclase -> subclase.famiCod == famiCod)
				.toArray(SubclaseModel[]::new);
	}
}
